"""Add column created_at to Comment

Revision ID: 5e8c9ea900bb
Revises: aa47a5d8eb87
Create Date: 2022-07-28 10:24:26.949494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8c9ea900bb'
down_revision = 'aa47a5d8eb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
