"""Add index to Post.created_at

Revision ID: 8cf52641840f
Revises: 5e8c9ea900bb
Create Date: 2022-07-28 10:25:52.313698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf52641840f'
down_revision = '5e8c9ea900bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_created_at'), 'post', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_created_at'), table_name='post')
    # ### end Alembic commands ###
